merge_protections:
  - name: Require a review from a maintainer.
    if:
      - base = main
    success_conditions:
      - approved-reviews-by = @Maintainer
  - name: Pull request title format.
    if:
      - base = main
    success_conditions:
      - "title ~=
        ^(fix|feat|docs|style|refactor|enhance|test|build|ci|chore|revert):"
queue_rules:
  - queue_branch_prefix: jeandle-jdk/merge-queue/
    merge_method: squash
    autoqueue: true
    update_method: rebase
    name: jeandle-jdk
merge_queue:
  max_parallel_checks: 5
